#!/usr/bin/ruby
require_relative "string_extend"
require_relative "text_data"

puts "
     SSSSSSSSSSSSSSS KKKKKKKKK    KKKKKKK     OOOOOOOOO          OOOOOOOOO     LLLLLLLLLLL                       999999999     
   SS:::::::::::::::SK:::::::K    K:::::K   OO:::::::::OO      OO:::::::::OO   L:::::::::L                     99:::::::::99   
  S:::::SSSSSS::::::SK:::::::K    K:::::K OO:::::::::::::OO  OO:::::::::::::OO L:::::::::L                   99:::::::::::::99 
  S:::::S     SSSSSSSK:::::::K   K::::::KO:::::::OOO:::::::OO:::::::OOO:::::::OLL:::::::LL                  9::::::99999::::::9
  S:::::S            KK::::::K  K:::::KKKO::::::O   O::::::OO::::::O   O::::::O  L:::::L                    9:::::9     9:::::9
  S:::::S              K:::::K K:::::K   O:::::O     O:::::OO:::::O     O:::::O  L:::::L                    9:::::9     9:::::9
   S::::SSSS           K::::::K:::::K    O:::::O     O:::::OO:::::O     O:::::O  L:::::L                     9:::::99999::::::9
    SS::::::SSSSS      K:::::::::::K     O:::::O     O:::::OO:::::O     O:::::O  L:::::L                      99::::::::::::::9
      SSS::::::::SS    K:::::::::::K     O:::::O     O:::::OO:::::O     O:::::O  L:::::L                        99999::::::::9 
         SSSSSS::::S   K::::::K:::::K    O:::::O     O:::::OO:::::O     O:::::O  L:::::L                             9::::::9  
              S:::::S  K:::::K K:::::K   O:::::O     O:::::OO:::::O     O:::::O  L:::::L                            9::::::9   
              S:::::SKK::::::K  K:::::KKKO::::::O   O::::::OO::::::O   O::::::O  L:::::L         LLLLLL            9::::::9    
  SSSSSSS     S:::::SK:::::::K   K::::::KO:::::::OOO:::::::OO:::::::OOO:::::::OLL:::::::LLLLLLLLL:::::L           9::::::9     
  S::::::SSSSSS:::::SK:::::::K    K:::::K OO:::::::::::::OO  OO:::::::::::::OO L::::::::::::::::::::::L          9::::::9      
  S:::::::::::::::SS K:::::::K    K:::::K   OO:::::::::OO      OO:::::::::OO   L::::::::::::::::::::::L         9::::::9       
   SSSSSSSSSSSSSSS   KKKKKKKKK    KKKKKKK     OOOOOOOOO          OOOOOOOOO     LLLLLLLLLLLLLLLLLLLLLLLL        99999999        
  ".gray
puts "Bienvenue sur la meilleure SKOOL. (forever number one) \n\n"

i = 0
while i < 1
    puts "Cette SKOOL était composée de #{@skoolers.join(', ')}, et évidemment  leur mentor Florent (FJA). Ils sont désormais partis dans les plus belles des tribus à travers OCTO, découvrez leurs histoires ici. \n"
    puts "Qui voulez-vous apprendre à connaitre ? [trigramme][ou quittez, tapez 'stop']".brown
    puts ">".gray
    @trigram = gets.chomp
    @trigram = @trigram.upcase

    if @trigram == 'STOP'
        puts "Au revoir"
        exit
    end
    if @trigram == "FJA"
        puts "Le meilleur mentor sans qui rien n'aurai pu arriver ! Florent Jaby, qu'on ne présente plus. <3 & Datalove".bg_magenta.black
        puts "#{@asciiPhotos[@trigram]} \n\n".bg_magenta.black 
    elsif @trigramList.key?(@trigram) == false
        puts "Cette personne n'est pas dans la meilleure skool (la SKOOL9), ou vous n'avez pas tapé un trigramme\n".red
        next
    end
    
    @filepath = "/usr/local/Cellar/skool/1.0.3c.tar/bin/contact_#{@trigram}.vcf"
    if @trigram != "FJA"
        @nameString = "#{@trigramList[@trigram]}".cyan
        puts "Vous voulez connaitre #{@nameString}.\n\n" 

        # VCARD Interesting lines
        # 4 : Fullname
        # 6 : Telephone
        # 7 : Email
        file = File.open(@filepath, "r")
        @vcfData = file.read.split("\n")
        tel = @vcfData[6].split(":")[1]
        email = @vcfData[7].split(":")[1]
        
        puts "Son téléphone : #{tel}".cyan
        puts "Son email : #{email}".cyan
        puts "#{@asciiPhotos[@trigram]}".gray
        
        puts "\n\n#{@updates[@trigram]}".brown
        puts "\n#{@bios[@trigram]}\n\n"
    end
    
    puts "Voulez-vous ajouter son profil dans vos contacts ? (macos seulement) [Y/n]".brown
    puts ">".gray
    @accept = gets.chomp
    if @accept.upcase === "Y"
        system "open #{@filepath}"
        if @trigram == "FJA"
            puts "Florent Jaby a été ajouté à vos contacts".green
        else 
            puts "#{@trigramList[@trigram]} a été ajouté à vos contacts".green
        end
    end
    puts "Voulez-vous voir le reste de la skool ? [Y/n]".brown
    puts ">".gray
    @exit = gets.chomp
    if @exit.upcase == "Y"
        next
    else
        puts "Au revoir"
        exit
    end
end 