#!/usr/bin/ruby
class String
    def black;          "\e[30m#{self}\e[0m" end
    def red;            "\e[31m#{self}\e[0m" end
    def green;          "\e[32m#{self}\e[0m" end
    def brown;          "\e[33m#{self}\e[0m" end
    def blue;           "\e[34m#{self}\e[0m" end
    def magenta;        "\e[35m#{self}\e[0m" end
    def cyan;           "\e[36m#{self}\e[0m" end
    def gray;           "\e[37m#{self}\e[0m" end
    
    def bg_black;       "\e[40m#{self}\e[0m" end
    def bg_red;         "\e[41m#{self}\e[0m" end
    def bg_green;       "\e[42m#{self}\e[0m" end
    def bg_brown;       "\e[43m#{self}\e[0m" end
    def bg_blue;        "\e[44m#{self}\e[0m" end
    def bg_magenta;     "\e[45m#{self}\e[0m" end
    def bg_cyan;        "\e[46m#{self}\e[0m" end
    def bg_gray;        "\e[47m#{self}\e[0m" end
    
    def bold;           "\e[1m#{self}\e[22m" end
    def italic;         "\e[3m#{self}\e[23m" end
    def underline;      "\e[4m#{self}\e[24m" end
    def blink;          "\e[5m#{self}\e[25m" end
    def reverse_color;  "\e[7m#{self}\e[27m" end
end

puts "
     SSSSSSSSSSSSSSS KKKKKKKKK    KKKKKKK     OOOOOOOOO          OOOOOOOOO     LLLLLLLLLLL                       999999999     
   SS:::::::::::::::SK:::::::K    K:::::K   OO:::::::::OO      OO:::::::::OO   L:::::::::L                     99:::::::::99   
  S:::::SSSSSS::::::SK:::::::K    K:::::K OO:::::::::::::OO  OO:::::::::::::OO L:::::::::L                   99:::::::::::::99 
  S:::::S     SSSSSSSK:::::::K   K::::::KO:::::::OOO:::::::OO:::::::OOO:::::::OLL:::::::LL                  9::::::99999::::::9
  S:::::S            KK::::::K  K:::::KKKO::::::O   O::::::OO::::::O   O::::::O  L:::::L                    9:::::9     9:::::9
  S:::::S              K:::::K K:::::K   O:::::O     O:::::OO:::::O     O:::::O  L:::::L                    9:::::9     9:::::9
   S::::SSSS           K::::::K:::::K    O:::::O     O:::::OO:::::O     O:::::O  L:::::L                     9:::::99999::::::9
    SS::::::SSSSS      K:::::::::::K     O:::::O     O:::::OO:::::O     O:::::O  L:::::L                      99::::::::::::::9
      SSS::::::::SS    K:::::::::::K     O:::::O     O:::::OO:::::O     O:::::O  L:::::L                        99999::::::::9 
         SSSSSS::::S   K::::::K:::::K    O:::::O     O:::::OO:::::O     O:::::O  L:::::L                             9::::::9  
              S:::::S  K:::::K K:::::K   O:::::O     O:::::OO:::::O     O:::::O  L:::::L                            9::::::9   
              S:::::SKK::::::K  K:::::KKKO::::::O   O::::::OO::::::O   O::::::O  L:::::L         LLLLLL            9::::::9    
  SSSSSSS     S:::::SK:::::::K   K::::::KO:::::::OOO:::::::OO:::::::OOO:::::::OLL:::::::LLLLLLLLL:::::L           9::::::9     
  S::::::SSSSSS:::::SK:::::::K    K:::::K OO:::::::::::::OO  OO:::::::::::::OO L::::::::::::::::::::::L          9::::::9      
  S:::::::::::::::SS K:::::::K    K:::::K   OO:::::::::OO      OO:::::::::OO   L::::::::::::::::::::::L         9::::::9       
   SSSSSSSSSSSSSSS   KKKKKKKKK    KKKKKKK     OOOOOOOOO          OOOOOOOOO     LLLLLLLLLLLLLLLLLLLLLLLL        99999999        
  ".gray
@skoolers = ['Antoine (ANBR)', 'Joseph (JORO)', 'Marta (MARL)', 'Michael (MIWE)', 'Sébastien (SEBA)', 'Stanislas (STAN)']
@bios = {
"ANBR" => "Antoine est titulaire d’un diplôme d’ingénieur généraliste en informatique (spécialité Business Intelligence et Data Science), obtenu en 2017 à l’Isep.

Il se forme au développement Web pendant un stage de 4 mois dans une startup. Puis pour approfondir ses compétences en développement web, il se déclare auto-entrepreneur et travaille pour insti7, une société de conseil en investissement financier. 
    
C’est lors de son dernier stage à la SG au Luxembourg que Antoine découvre son intérêt pour la data, notamment le machine learning (deep learning). A travers cette expérience, il poursuit sa montée en compétence en développement.
    
Désormais consultant OCTO, il découvre avec grand intérêt les méthodologies agiles, le TDD et autres bonnes pratiques du développement.", 
"JORO" => "Diplomé d’un Master MIAGE à l’université Paris-Sud XI en 2014, Joseph commence sa carrière au sein d’Engie en se concentrant sur les aspects fonctionnels de l’IT. En tant que Business Analyst, il pilote des projets et contribue à traduire des besoins métiers en produit. 
Il choisit ensuite d’aller dans le concret et de s’orienter sur le développement.

Il réalise une mission au sein d’Engie Digital. Entouré par des consultants seniors, il travaille sur le développement d’une application Big Data en utilisant les bonnes pratiques de CI, Craftsmanship et d’agilité. 
Fort de cette expérience, Joseph prend le tech leading d’un projet d’optimisation de centrales : cadrage, montée en compétence de l’équipe, choix d’architecture et développement.

Son parcours continue maintenant chez OCTO avec 2 objectifs principaux : découvrir de nouveaux contextes fonctionnels et renforcer son expertise.", 
"MARL" => "Marta est diplômé de l’Ecole Centrale Nantes en 2015, c’est là qu’elle découvre le code à travers la programmation d’un jeu en C.

Elle débute sa carrière en 2016 chez Sopra Steria en tant qu’ingénieur études et développement Java où elle travaille sur plusieurs projets pour réaliser des applications de référence à la CNAM. Sa rapide montée en compétences lui permet de devenir référente technique et d’être l’interface privilégiée avec le client. En parallèle, elle découvre la méthologie agile au sein de ses différents projets chez SopraSteria. Elle commence également à s’intéresser aux bonnes pratiques et au software craftmanship.
    
Elle rejoint OCTO Technology en 2018 pour renforcer son expertise dans le développement web et notamment côté front.", 
"MIWE" => "En 2012, Mickaël est diplômé d’un master en Management des Systèmes d’information à l’Exia.Cesi de Nancy. Il commence son parcours professionnel en tant que MOA au Ministère de la Défense puis en tant que Proxy Product Owner chez ALD Automotive (Société Générale), ce qui lui permet d’avoir une vision globale des projets IT. 

En parallèle, il acquiert une expertise dans le développement FullStack grâce aux missions qu’il réalise en auto-entrepreneur et à sa veille technologique. Il participe à divers projets sur les technologies : Scala, Java, PHP, ReactJs, React Native, Angular ou encore Neo4j. 
Il accompagne notamment une jeune startup sur le développement d’un MVP pour une application mobile en React Native. Il lead le cadrage de l’application, forme et assure le suivi de l’équipe sur les pratiques de Software Craftsmanship et d’agilité.
    
Mickaël fait le choix de rejoindre OCTO, où il se reconnaît dans les valeurs agiles, les pratiques de développement et la vision d’entreprise. 
Il s’attache en priorité à l’expérience utilisateur et à la qualité du produit qu’il délivre. Mickaël s’intéresse également à fluidifier le processus de développement via les méthodes agiles et à ses compétences de développeur FullStack. 
    
Pour finir, il est actif sur différents réseaux sociaux tels que LinkedIn et Stack Overflow.", 
"SEBA" => "Sébastien a suivi une formation généraliste dans le domaine du multimédia et de l'information-communication, dont il ressort diplômé en 2011, et commence sa carrière dans le code.

En 2017, il prend le poste de Directeur des Systèmes d'Information au sein des Scouts et Guides de France, où il accompagne une équipe pluridisciplinaire. Il y acquiert une vision projet 360 qui lui permets de discuter facilement avec les sponsors, le métier, et les équipes de delivery (PO, devs, ops, designers), et de comprendre leurs enjeux et besoins.
    
Curieux de nature et passionné par la résolution de problèmes, il revient finalement à sa première spécialité : le développement. Il profite de cette curiosité et de son expérience pour approfondir de nouveaux domaines : UX design, management, pratiques devops, APIs REST, protocoles réseaux, systèmes d'informations géographiques, … 
    
Sébastien cherche aujourd'hui à appliquer son expertise dans des équipes agile, notamment sur des projets d'API qui le passionnent particulièrement.", 
"STAN" => "Passionné par le domaine informatique depuis toujours, Stanislas décide de se former au développement d’applications web après avoir quitté le métier de comédien. Il se forme chez Simplon.co où il acquiert, par la pratique, de nombreuses compétences techniques mais également des méthodologies de travail agiles.

Stanislas rejoint ensuite l’équipe de Begood, dispositif digital pour améliorer l’expérience apprenante, dans le but d’offrir aux rédacteurs un moyen de modifier eux-même leur parcours de formation par le développement d’un outil d’édition du contenu.
Cette expérience lui permet d’apporter son expertise en JavaScript mais également, en travaillant aux côtés de développeurs seniors, de se former à AngularJS et TypeScript.
    
Comédien pendant 5 ans, Stanislas croit au travail en équipe, porté sur l’humain, et au partage des connaissances. À l’écoute, passionné et pédagogue, il souhaite poursuivre le développement d’applications web, sur des technologies front-end et back-end."}
@trigramList = {"ANBR" => "Antoine Bres", "JORO" => "Joseph Robert", "MARL" => "Marta Larranaga", "MIWE" => "Michael Wegerich", "SEBA" => "Sébastien Bartoli", "STAN" => "Stanislas Chable"}
@asciiPhotos = {
    "ANBR" => "               *&&@@&&@@@&&@@@@@@&@@@@@@@@@@@&.            
              /&%&&&&@@@@@@@@@@@@@@@@@@@@@@@&@&            
             ,%&@@@@@@@@@@@@@@@@@@@@@&@&@&&@@@&%           
            /&&@@&@@@@@@@@@@@@@@@@&&@&&&&&&&&&&&%          
            *&&@&%%%%##%&&&&%%%%####%%&&&&&&@@&&&%         
            %&((/////(#####(((((((####%&@@@@@&&&         
           ,&&&/****,*////////((/////(/((#&@@@&&@&.        
           .&****,,,****///*******////((%&@@@@&@.        
            &**,,,,,,,*********///*/**//(&@@@@@@         
            %@%*,,**////****/(#%&&%%%%%%#(/#@@@@@@.        
            .@&*#(##(((((/*/(#%%#%#&&&%##(//#@@@@%#*       
             (&,*(#%%@//,,*(##%&(%%%###(/*/&&@@%%&       
            ,/&,*/*//((/**,,*//(###((///****/#&&%%#(       
            #(%,,,,,*/*,,,,,*///**//******///(#(&.       
            ,(#,,,,,,,,,,*..*/(((///****/////((#/#(        
             *#,,,*,,,,,*,.,****/((((///((((((###(.        
              #*,****,,,,/((#%&%#//////(((((((.            
              *******,...,**/(((/////(/(((#((/             
                 ,***,,,,,*/**(###(##((((((((*             
                  ***,,*(#####(//((((((((((((/             
                   ***,*,***/(((##((((((((((((.            
                    ,*****//(((((//////(((####*,           
                    ,/**,,,,,,////////((#%####,.&,         
              ./##%,(///*****/((((%###%%%%##(,,.#%,        
    .,/(##%%%%%%%((.(%//////(((###%%%######,,,,,&&&(       
#((###%%%%%%%%%((%. .&*******///(((#####/.....,&&&&&%      
##%%%%%%%%%%%##%%%   ,#*******//(((##/ ......,%&&&&&&%%*   
%%%%%%%%%%%%%%%%%(    .#*/*****///,  ......,*&&&&&&&&&&&&%#
%%%%%%%%%%%%%%%%&.(((#,.*//****.     ....,,(&&&&&&&&&&&&&&&",
    "MARL" => "                /%%(((//////((((#&&&&%&.                   
               #%(((///////////(((#%&&%(,                  
              /%#/(///*******///(((#%&&(%,                 
              #%#((////******///(((#%&&%%&,                
              (%#(((///*****//#(#(((%&&%@&%                
             ,&#(//((//*///////((((&&&%&&%               
             &%%%(##%%(#(/#((/%###(#(%&#%%/              
             ##((((((%(/(#((////(((#%%%##%*              
            ,%((//////((//((////////((#(((%#*              
          ,(#%%(/(/////(/*/((***///((##/(#%%/,             
        .*(%&&&&/(/////(((/(//**///(##((&%&%#,.            
        (%%%%&&@@(////////////////((#@@@&&@&,            
       .(%##%&&&@%(/*/(((//(((/*//((%&@@@&&&&&(.           
       */%%#%%&&&%#(/////////////((%%&&&&&&&&&%,.          
        .(%%&%&&%%%%((///*/////((%#(&&&&&&&&&&&,,          
         .(%&&%&&%%&&((//////(##(((%%&&%&&%&&&%/,,         
          .%%%&&%&%%%((((//////(((#%&%&%%&&%&&%#/*.        
         .*#(%&&&&&&&(///(////((/(%%&&%%&&&%#%#/((,        
       .*((,(&&&&@&&//////*/////(%&&%%&&&&&%%#/((*       
     ,  ..,/%&&@@@@&&%(///////////(%%%%%&&&&&&&%#,*(/      
       ,(#%%&&@@@&&&&&&///////////%#&%&&&&&&&&%%%%#/     
    .(#%%%&&&&&@&@&&&%&&%//////**///%#&%&&&&&%&&&%&/(((,.  
 .,(((#&&&&&&&&&&&&&@@@%#*********/(%#&&&&%&&&&&&%#**/#(// 
*(%##%&%&&&&&&&&&&&&&&%##//********/(##&%&%%&%&%%%%#((*(#/(
%##%%#%&&&&%&&%&&&&&%((//***/*****///*/%%&&%&&%%%#((((((((#
#%%%%%%#%%&&&&&&&&#/(*/********//****/%&&&%&/#(/*(/
(#(%%%%%(##&&&@&&&&&&(///********/*/**/#%&&%%%%%&(##/(/((&%
##(%%%&(%%%&%&&%&&&&%#(%&&%#//////((#&&&&&&&%%%%/(#((%%((((
#(###&%#/%(%%&&&&&&@&(((##########*%%%&&&@&&%#%***%#((((###",
    "SEBA" => "                   , ,,  .                                 
              .   ,  .     ..                              
            .     ....,.,,,,.,                             
            ..  .#&%%%((/(((/****,,,,,*.                   
           ,. .,&&&&&&%%%%%#(((/////////*                  
           ,*,,&&&&&&&&%%%%%%##(((((///(/*                 
          . ,/%&&&&&&&&&%%%%%%####((((((//,                
            *(%&&&&&&&%%%%%%%%###(((((((((* .              
           ,*(%&&&&&&&&%%%%%%%%###(((((###(,               
            *%&&&&&&&&&&%%%%%%%%%%##(//((##*               
            .&&&(,,...,,//###%#(/*... .,.##(               
             %&##&%(/.,.*#%&%##(/.(**(#&%(%(               
          (*./&&&*(@/ ,/*/&@%((,,/..%&#*&&%#  *%           
          ./(/&&@&&%#/**(&&&#(((*,//(##%#%##((*/           
           (@/&&&&&&&%&&&&&&%((#((((########/#%(           
           #&*%&@@@&%&%&&&&&%(((#((((##%%%###*(            
            @#%&&@@&&%##&&&@&##%#(((##%#%###%%             
            #&(&&&&&&%#%%%.%%###((#(#%%%#%%(%#             
              ,%&&&&%%&&&&&%(/(///((##%%%(%*               
               %&&&&&##%&&&&#(###(#//##&###                
             .**%&#&#(#(#(//(/*.,/*#(#%%##*.               
        (%&#&.%,*##%&%&&&%&#(((((%%#%%%##,,#.*/,/,,        
   .%%(&@%.&.&(@.*(%&%%%&%%##((#%%#%%##/# ./#.#%%//,. ,    
##@,//&..@&#,@#&.#&##%&&&&&&%%###%(%#*%%% ..* ,%.((*.(%/#*.
&%%@%*/@@.@(#/&,.#&&&#*%####(/(/(**(%%%&(  %#&,( ,#.#  (,%(
@@#.&%,#&.@/@*@/#.&&&&%%(..,...,(%%%%%%#/  ,(&/% *&*(&,&(./
/@%,@&/@&,@%@,@(% (&&%%&%%&&%#(%%%%%###(   *@%,*  (,.%(.@*/
,%#.%#.##.,*&.&,(  *%%%%&&%%%##%%%####(,    %&(&..%%,##.#(,
,@&.&@*&@.,@@#%&@,..*(#%%%%####%#####(,..,(.%%%&,.&&,&@,@#,",
"MIWE" => "#####(((//////////*,     .............     *(((((((((((((((
######(((//////,   ..............,,,,,,,,,,.   /(((((((((((
######((((((*   ....,*(###########(/,,,,,,,,,,,   (((((((((
######((((.  ..,,,/######(((#((####%##(,,,,,,,,**,  /((((((
######((,  ....,(((#(#(#((((#(((###%%####,**********  /((((
######(  .....,(###########((/**//(/(((((#********///*  (((
#####*  ,...../##%%%%%%%%%%#((/****************#(%%%%%%  ((
####, ,**.....#%%%%%%%%%&%%%##((((((//////*****(%%%##((#. /
###* ,***,.../%%%%&&&&&&&&&&%###((((///****,    (##%%%%%%. 
##( .,***,.../%%&&&&&&&&&&%%%###(((///****/****/%%%%%%%%%% 
##  ,****,./####(#&&&&&%%#######%%%&&%(((%/***%%%%&%%%%&%
#( .**/(/(#%%%%%%&%&&&&%%%%%%%%&%%%&&%(#&(,,,,%%%&&&&&%%&
(. /(((###%&%#&%%#%&%%%%%%%%%####%###%%%(((***,*%%%&&&&&&&/
(  (#####%###%&&&&%%&&&&&&%%%%##((/((#%#%#/,**,*%%%%&&&&&&(
#  ##%%%%%%%%%&&%%%&&&&&&&&%%##(//(%%%%#(/****%&&&&&&&&&(
   &%%%%&&%%%#%@&&&&&&&&&&&&%%%#((#%&&&&%(****%&&&&&&&&
   &&&&&%&&&%%%#&&&&&&&&&&&&&&&%%#%%%%%%#(//////%&&&&&&&&&%
   ,&&&&@&&&&&&&@&&&&@&&&&&&&%%##%%%%%#(//////%&&&&&&&&&&
    %&@@@@@@&&&@&&@@&&&@@@&&&&&&&%%%#####(///#/(%&&%&&&&&
     &&@@@@@%&@@@&&&&&&&&&@@&&&&&&&%%#(( ,/*##   %%%&&&&&& 
     .&&@@@@#@@@@@@&&@@&&&&&&&&&&&&&&%#%(,//#%,,,&&&&&&&&  
      .&&@@@%&@@@@@@@@@@@&&&&%&&&%&@&&&&&*/*#%***&&&&&&&   
        &@@@@@@@@@@@@@@&&&&@&&&%@@&&&&&(/,/%,,,%&&&&%    
         /@@%&%@@@@@@@@@@@@&@@&%&&@&&&&&&&%.,#.  (%%&.     
           #&@%@@@@@@@@&&@@@&@&&&@@&&&&&&&,(*,.*(,       
             *@@@@@@@@@@&@@@@&&&@@&&&&&&%&&&%*,,,          
                (@@@@@@@&@@@@&&@@@@&&&&&&&&&&%.            
                    #@@@@@@@@&@@@@&&&&&&&&*                
                   .      ./#%&&&%(*                       ",
"JORO"=> "////((/(((((/(((((((((((((((((((((#///.,*////////*********,
(/////((/(((((((/(((((((((((((((((((###//*.**//////********
****//////////////#%%%#%#(((((((((((((((###/.,,**//********
**********///(%&&&&&@@%@&%&@%#/((((((((((((/ ((*/.,********
,,,*******/(#%&@@&@@@@@@@@&&@&&&*((((((((((* (((((/*/.*****
,,,,,,,,,*/%&@@@@@@@@@&%###%&&@@&*   /(((((* (((((((((//*,*
,,,,,,,,,/#%&@@@&%#(/**,,.,,,,,*&%       ,(* ((((////((/(*,
(,,,,,,,,%%&@@%#(//**,,,,.....,,.%/       /* ////////////*.
,,,,,,,,#%&&&&(/////**,,,,,,,.,,..(///((///* ,,**********,.
,,,,,./.(%&@@%(/////***,,,,,,,,,,.(*///////, ,,,,,,,,,,,*,.
......../%&@@#(((//////**,,**/#%&%&&////***,    ,,,,,,,,,.,
,,,      %&@%(((%&@&&@@@&@@@@%%%(/*(#%*****, *((#*   .,.,,.
,,,.,    #@(##%%&@@&&&&@/,@%%#(*,,#****,*, *******/(#*   
,,,#%   ((%((&%%%###%%&&(**&****,,/**.,,*,.*/#@@@@@@&*//.
**%%(   %##%#((/#//////%%#(/*,///*,.***    ,.%@@@@@@&&@//*,
#%%&,    #%%(((((((//(((%#(**,,***,.***    ,.(&&&&&&&@@/,*,
%%%&     .#%%###(((((//(%%&%#//,,,,,***    ,,/&&&&&&&@&*.*/
%#%&       ########(((/(#%&%#%((((,,***    ,,*&&&&&&&@&/.*(
##%&          #####(((%###%%%#/*,,*/*,*((((*,,&/(&&&&&.,(
##%@@&&&&&&&%%#%######((((((%#/,,,//,,*((((*,./#/#&&&&&%.,/
###############(%%%#####((////*,,(*/,,*((((**.%//*&&&&&&,%*
##############%(##&&&&%#((((/(((/,@&,,*((((*, &&&%&%&&&&,,,
###/(####%@@@@@#(###%&@@@&&%&/*,,,@@@&@#(#(/, &&%%&%&&@&..,
/,,,*/#@@@@@@@@@#(####%%##(/***,,#@@@@@@@@&%, %%%%%%%&&&,.*
,,.,%@@@@@@@@@@@@(######/***,/@@@@@@@@@@@@@@&&%%%&&&&&,.,
&&@@@@@@@@@@@@@@@@@@####((//(@@@@@@@@@@@@@@@@@@@&&%%%&&&*.,
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&%&&/.,
&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&%(.,
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&%,,",
"STAN" => "*,,,,,,,,,,,,,,,,,,,**//#(/##(##((##%(((##(/*,,**,,,,,,****
*,,,,,,,,,,,,,,,,****/(###(%#(#/#%%%#%%(###%%/******,,,,**/
,,,,,,,,,,,,,,,,,,**/(((((/(//,(##%&&%(#(#(%&%##//,,,,,*(((
,,,,,,,,,,,,,,,,,****/(###%(%#/*(%%&&@@@%(#%&%%%%(**,,,*(#(
,,,,,,,,,,,,,,,,,,,**/((###%###(/(%%&&@@#%#%&%&%#(*****//
,,,,,,,,,,,,,,,,,****/////(((##%%######%#%%%%%&&&%#/*****
,,,,,,,,,,,,,,,,,****,,,,,*//((((((######%%%%&@&&&&&/****
,,,,,,,,,,,,,,,,,***.......,,,***/////((##(#%&&@@&&&@%#(/**
,,,,,,,,,,,,,,,,,**      ...,.,,****///(((((#%%%%%%%%%(**,,
,,,,,,,,,,,,,,,,,,/     .......,,,**///////(%#%%##%%%#/,,,,
,,,,,,,,,,,,,,,,,,..,,,*,......,,,***//////(%%%&%%%%%(*,,,,
,,,,,,,,,,,,,,,,,,...,,,......*/((#(((#(///((%&@&&&&%/,,,,,
,,,,,,,,,,,,,,,,,,.../((*. .,*////((((//((//(%&&&%(/*,,,,,,
,,,,,,,,,,,,,,,,,. ..,,,.  ,//(/***/((#((////#%#(/(,,,,,,,,
,,,,,,,,,,,,,,,,,         .*///////////////////((//,,,,,,,,
,,,,,,,,,,,,,,,,,    ..   ,////**,,,,**////////(((*,,,,,,,,
,,,,,,,,,,,,,,,,,..,,.   .*//////*,,,**//////////*,,,,,,,,,
,,,,,,,,,,,,,,,,,,.*.....,*//(((//*,,**///////,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,..,,..,***/(///////,*/*///*,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,.  ...,,**//(%&/*,*/**////*,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,.   ..,*//(//**,*****/////**/**,,,,,,,,
**,,,,,,,,,,,,,,,,,,,.  ....,,*****//***//////***/&&&%#(*,,
,,,,,,,,,,,,,,,,,,,,,/   .,,*******/**///*//*******&&&&&&&%
**,,,,,,,,,,,,,,,,*//,   ..,,****///*///**(/********%&&&&&%
***,,,,,,,,,,,**/((/* .,.,,,,*//*****//**/(*********/#&&&%%
*****,,,,,,*/*/(##(/  */(...,*********/*/((***********#&%%%
******,**//////(##(  .,*%(,. .,,,,******/**,,*********/#%%%
    .*///////(/(#%,  ..,(#(*....,,*****//.,,,,,*/(##((//%%%
...*///////((##((*.,,.,,*%#(*,,,*******/*.#&@@@@@@@&&&%%%##"
}

puts "Bienvenue sur la meilleure SKOOL. \n\nCette SKOOL est composée de #{@skoolers.join(', ')}\n"

i = 0
while i < 1
    puts "Qui voulez-vous apprendre à connaitre [trigramme]? (ou quittez, tapez 'stop')".brown
    puts ">".gray
    @trigram = gets.chomp

    if @trigram == 'stop'
        exit
    end
    if @trigramList.key?(@trigram) == false
        puts "Cette personne n'est pas dans la meilleure skool (la SKOOL9), ou vous n'avez pas tapé un trigramme\n".red
        next
    end

    @nameString = "#{@trigramList[@trigram]}".cyan
    puts "Vous voulez connaitre #{@nameString}.\n\n" 

    # VCARD Interesting lines
    # 4 : Fullname
    # 6 : Telephone
    # 7 : Email
    @filepath = "/tmp/skool9-contacts/contact_#{@trigram}.vcf"
    file = File.open(@filepath, "r")
    @vcfData = file.read.split("\n")
    tel = @vcfData[6].split(":")[1]
    email = @vcfData[7].split(":")[1]
    
    puts "Son téléphone : #{tel}".cyan
    puts "Son email : #{email}".cyan
    puts "#{@asciiPhotos[@trigram]}".gray

    #system "cat", "#{@filepath}"
    puts "\n\n#{@bios[@trigram]}\n\n"
    puts "Voulez-vous ajouter son profil dans vos contacts ? [Y/n]".brown
    puts ">".gray
    @accept = gets.chomp
    if @accept === "Y"
        system "open #{@filepath}"
        puts "#{@trigramList[@trigram]} a été ajouté à vos contacts".green
    end
    puts "Au revoir"
    exit
end 